[package]
name = "rust_algo"
version = "0.1.0"
authors = ["Khoa Le <kdl2483@truman.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
